#!/bin/sh
# Copyright (C) 2000-2020 Synology Inc. All rights reserved.

APP_NAME=HomeLibrary
APP_DIR=/var/packages/$APP_NAME/target

case $1 in
	start)
		### Start this package.
		# run start command
		cd $APP_DIR/system/api
		npm run start:prod
		echo "The package HomeLibrary has been started" > $SYNOPKG_TEMP_LOGFILE
		exit 0
	;;
	stop)
		### Stop this package.
		# run stop command
		cd $APP_DIR/system/api
		npm run stop:prod
		echo "The package HomeLibrary has been stopped" > $SYNOPKG_TEMP_LOGFILE
		exit 0
	;;
	status)
		### Check package alive.
		# run status command
		exit 0
	;;
	killall)
        ;;
	log)
		exit 0
	;;
esac

